// MOKSHA — 45 aides financement (données statiques pour matching côté client)

export type ProfilType = 'particulier' | 'entreprise' | 'association' | 'etudiant'
export type SituationType = 'salarie' | 'demandeur_emploi' | 'independant' | 'auto_entrepreneur' | 'retraite' | 'rsa' | 'cej' | 'etudiant'

export type Aide = {
  id: number
  nom: string
  type_aide: 'formation' | 'numerique' | 'social' | 'fiscal' | 'subvention' | 'pret' | 'accompagnement'
  profil_eligible: ProfilType[]
  situation_eligible: SituationType[]
  montant_max: number
  taux_remboursement?: number
  url_officielle: string
  description: string
  region?: string
  handicap_only: boolean
  cumulable: boolean
  badge: 'probable' | 'possible' | 'verifier'
}

export const AIDES_DATA: Aide[] = [
  // PARTICULIERS (20)
  { id: 1, nom: 'CPF — Compte Personnel de Formation', type_aide: 'formation', profil_eligible: ['particulier'], situation_eligible: ['salarie', 'demandeur_emploi', 'independant', 'auto_entrepreneur'], montant_max: 5000, url_officielle: 'https://www.moncompteformation.gouv.fr', description: 'Formation professionnelle financée par vos droits acquis.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 2, nom: 'AIF — Aide Individuelle à la Formation', type_aide: 'formation', profil_eligible: ['particulier'], situation_eligible: ['demandeur_emploi'], montant_max: 8000, url_officielle: 'https://www.pole-emploi.fr/candidat/en-formation/les-aides-a-la-formation/laide-individuelle-a-la-formatio.html', description: 'France Travail finance votre formation quand le CPF ne suffit pas.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 3, nom: 'Chèque numérique CAF', type_aide: 'numerique', profil_eligible: ['particulier'], situation_eligible: ['salarie', 'demandeur_emploi', 'rsa', 'cej'], montant_max: 500, url_officielle: 'https://www.caf.fr', description: 'Aide pour l\'équipement numérique et la formation digitale.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 4, nom: 'Pass Numérique', type_aide: 'numerique', profil_eligible: ['particulier'], situation_eligible: ['salarie', 'demandeur_emploi', 'retraite', 'rsa'], montant_max: 20, url_officielle: 'https://www.inclusion-numerique.fr', description: 'Chèques pour accéder à des services de médiation numérique.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 5, nom: 'Prime d\'activité', type_aide: 'social', profil_eligible: ['particulier'], situation_eligible: ['salarie', 'auto_entrepreneur', 'independant'], montant_max: 600, url_officielle: 'https://www.caf.fr/aides-et-services/s-informer-sur-les-aides/solidarite-et-insertion/la-prime-d-activite', description: 'Complément de revenus pour les travailleurs modestes.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 6, nom: 'AGEFIPH — Aide création d\'activité', type_aide: 'subvention', profil_eligible: ['particulier'], situation_eligible: ['salarie', 'demandeur_emploi', 'independant', 'auto_entrepreneur'], montant_max: 10000, url_officielle: 'https://www.agefiph.fr', description: 'Aide à la création d\'entreprise pour les personnes en situation de handicap.', handicap_only: true, cumulable: true, badge: 'probable' },
  { id: 7, nom: 'FIPHFP', type_aide: 'subvention', profil_eligible: ['particulier'], situation_eligible: ['salarie'], montant_max: 10000, url_officielle: 'https://www.fiphfp.fr', description: 'Fonds pour l\'insertion des personnes handicapées dans la fonction publique.', handicap_only: true, cumulable: true, badge: 'verifier' },
  { id: 8, nom: 'Mobili-Jeune', type_aide: 'social', profil_eligible: ['particulier', 'etudiant'], situation_eligible: ['etudiant', 'salarie'], montant_max: 1200, url_officielle: 'https://www.actionlogement.fr/aide-mobili-jeune', description: 'Aide au logement pour les jeunes de moins de 30 ans en formation.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 9, nom: 'Aide CROUS', type_aide: 'social', profil_eligible: ['etudiant'], situation_eligible: ['etudiant'], montant_max: 5000, url_officielle: 'https://www.etudiant.gouv.fr', description: 'Bourse sur critères sociaux pour les étudiants.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 10, nom: 'Pass Culture', type_aide: 'numerique', profil_eligible: ['particulier', 'etudiant'], situation_eligible: ['etudiant', 'salarie', 'demandeur_emploi'], montant_max: 300, url_officielle: 'https://pass.culture.fr', description: 'Crédit pour les jeunes de 15 à 20 ans pour l\'accès à la culture.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 11, nom: 'Microcrédit professionnel', type_aide: 'pret', profil_eligible: ['particulier'], situation_eligible: ['demandeur_emploi', 'rsa', 'auto_entrepreneur'], montant_max: 5000, url_officielle: 'https://www.adie.org', description: 'Prêt professionnel pour les exclus du système bancaire classique.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 12, nom: 'OPCO — Prise en charge formation', type_aide: 'formation', profil_eligible: ['particulier'], situation_eligible: ['salarie'], montant_max: 5000, url_officielle: 'https://travail-emploi.gouv.fr/ministere/acteurs/partenaires/opco', description: 'Votre OPCO finance la formation de vos salariés.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 13, nom: '1jeune1solution', type_aide: 'accompagnement', profil_eligible: ['particulier', 'etudiant'], situation_eligible: ['demandeur_emploi', 'etudiant', 'cej'], montant_max: 4000, url_officielle: 'https://www.1jeune1solution.gouv.fr', description: 'Aides à l\'emploi, à la formation et à l\'accompagnement des jeunes.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 14, nom: 'Garantie Jeunes (CEJ)', type_aide: 'social', profil_eligible: ['particulier'], situation_eligible: ['cej', 'demandeur_emploi'], montant_max: 6000, url_officielle: 'https://www.service-public.fr/particuliers/vosdroits/F32700', description: 'Contrat d\'Engagement Jeune — jusqu\'à 500€/mois pendant 12 mois.', handicap_only: false, cumulable: false, badge: 'probable' },
  { id: 15, nom: 'PLIE — Plan local pour l\'insertion', type_aide: 'accompagnement', profil_eligible: ['particulier'], situation_eligible: ['demandeur_emploi', 'rsa'], montant_max: 3000, url_officielle: 'https://travail-emploi.gouv.fr', description: 'Parcours individualisé vers l\'emploi avec accompagnement renforcé.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 16, nom: 'RSA — Complément activité', type_aide: 'social', profil_eligible: ['particulier'], situation_eligible: ['rsa', 'auto_entrepreneur'], montant_max: 7200, url_officielle: 'https://www.caf.fr/aides-et-services/s-informer-sur-les-aides/solidarite-et-insertion/le-revenu-de-solidarite-active-rsa', description: 'Cumul RSA + revenus d\'activité pendant les premiers mois.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 17, nom: 'FNE-Formation 100%', type_aide: 'formation', profil_eligible: ['particulier'], situation_eligible: ['salarie'], montant_max: 10000, url_officielle: 'https://travail-emploi.gouv.fr/emploi-et-formation/formation/fne-formation', description: 'Formation 100% prise en charge pour les salariés en activité partielle.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 18, nom: 'Transition Professionnelle 100%', type_aide: 'formation', profil_eligible: ['particulier'], situation_eligible: ['salarie'], montant_max: 20000, url_officielle: 'https://www.transitionspro.fr', description: 'Financement à 100% pour une reconversion professionnelle.', handicap_only: false, cumulable: false, badge: 'possible' },
  { id: 19, nom: 'VAE — Validation des Acquis', type_aide: 'formation', profil_eligible: ['particulier'], situation_eligible: ['salarie', 'independant', 'auto_entrepreneur'], montant_max: 3000, url_officielle: 'https://vae.gouv.fr', description: 'Obtenez un diplôme grâce à votre expérience professionnelle.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 20, nom: 'Prêt d\'honneur France Active', type_aide: 'pret', profil_eligible: ['particulier'], situation_eligible: ['demandeur_emploi', 'auto_entrepreneur', 'independant'], montant_max: 10000, url_officielle: 'https://www.france-active.org', description: 'Prêt à taux zéro pour lancer votre activité.', handicap_only: false, cumulable: true, badge: 'probable' },

  // ENTREPRISES (15)
  { id: 21, nom: 'France Num — Chèque numérique', type_aide: 'numerique', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'auto_entrepreneur', 'salarie'], montant_max: 6500, url_officielle: 'https://www.francenum.gouv.fr', description: 'Aide à la transformation numérique des TPE/PME.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 22, nom: 'Pack IA Entreprise', type_aide: 'numerique', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 18500, url_officielle: 'https://www.bpifrance.fr', description: 'Financement pour l\'intégration de l\'IA dans votre entreprise.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 23, nom: 'OPCO — Formation salariés IA', type_aide: 'formation', profil_eligible: ['entreprise'], situation_eligible: ['salarie', 'independant'], montant_max: 8000, url_officielle: 'https://travail-emploi.gouv.fr/ministere/acteurs/partenaires/opco', description: 'Financement formation IA pour vos équipes via votre OPCO.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 24, nom: 'Aide Région BFC Numérique', type_aide: 'numerique', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'auto_entrepreneur', 'salarie'], montant_max: 5000, url_officielle: 'https://www.bourgognefranchecomte.fr', description: 'Aide régionale pour la transformation numérique.', region: 'Bourgogne-Franche-Comté', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 25, nom: 'CIR — Crédit Impôt Recherche', type_aide: 'fiscal', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 100000, taux_remboursement: 30, url_officielle: 'https://www.enseignementsup-recherche.gouv.fr/cir', description: '30% de crédit d\'impôt sur vos dépenses de R&D.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 26, nom: 'CII — Crédit Impôt Innovation', type_aide: 'fiscal', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 80000, taux_remboursement: 20, url_officielle: 'https://www.enseignementsup-recherche.gouv.fr/cir', description: '20% de crédit d\'impôt sur vos dépenses d\'innovation.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 27, nom: 'FNE-Formation IA', type_aide: 'formation', profil_eligible: ['entreprise'], situation_eligible: ['salarie'], montant_max: 15000, url_officielle: 'https://travail-emploi.gouv.fr/emploi-et-formation/formation/fne-formation', description: 'Formation IA financée à 100% pour les salariés.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 28, nom: 'Chèque TPE CCI', type_aide: 'accompagnement', profil_eligible: ['entreprise'], situation_eligible: ['auto_entrepreneur', 'independant'], montant_max: 1500, url_officielle: 'https://www.cci.fr', description: 'Aide CCI pour accompagner les TPE dans leur développement.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 29, nom: 'AGEFIPH Entreprise', type_aide: 'subvention', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 10000, url_officielle: 'https://www.agefiph.fr', description: 'Aide aux entreprises employant des travailleurs handicapés.', handicap_only: true, cumulable: true, badge: 'probable' },
  { id: 30, nom: 'DIRECCTE — Aide à l\'embauche', type_aide: 'subvention', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 8000, url_officielle: 'https://travail-emploi.gouv.fr', description: 'Aide directe à l\'embauche dans les zones prioritaires.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 31, nom: 'Diagnostic Numérique BFC 50%', type_aide: 'accompagnement', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 3000, taux_remboursement: 50, url_officielle: 'https://www.bourgognefranchecomte.fr', description: 'Diagnostic numérique subventionné à 50% par la Région.', region: 'Bourgogne-Franche-Comté', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 32, nom: 'BPI France — Prêt Innovation', type_aide: 'pret', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 300000, url_officielle: 'https://www.bpifrance.fr', description: 'Prêt à taux avantageux pour financer l\'innovation.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 33, nom: 'DETR — Dotation Équipement Territoires', type_aide: 'subvention', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 50000, url_officielle: 'https://www.collectivites-locales.gouv.fr', description: 'Subvention pour les entreprises en zone rurale.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 34, nom: 'FEDER — Fonds européen', type_aide: 'subvention', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 100000, url_officielle: 'https://www.europe-en-france.gouv.fr', description: 'Fonds européen pour le développement régional.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 35, nom: 'Aide numérique Santé', type_aide: 'numerique', profil_eligible: ['entreprise'], situation_eligible: ['independant', 'salarie'], montant_max: 15000, url_officielle: 'https://esante.gouv.fr', description: 'Aide à la numérisation pour les professionnels de santé.', handicap_only: false, cumulable: true, badge: 'possible' },

  // ASSOCIATIONS (10)
  { id: 36, nom: 'FDVA 2 — Fonctionnement innovation', type_aide: 'subvention', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 15000, url_officielle: 'https://www.associations.gouv.fr/fdva.html', description: 'Subvention pour le fonctionnement et l\'innovation des associations.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 37, nom: 'FDVA 3 — Formation bénévoles', type_aide: 'formation', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 5000, url_officielle: 'https://www.associations.gouv.fr/fdva.html', description: 'Financement de la formation des bénévoles.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 38, nom: 'Subvention communale', type_aide: 'subvention', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 5000, url_officielle: 'https://www.associations.gouv.fr', description: 'Subvention de fonctionnement par votre commune.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 39, nom: 'LEADER — Programme européen rural', type_aide: 'subvention', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 20000, url_officielle: 'https://www.europe-en-france.gouv.fr', description: 'Programme européen de développement rural.', handicap_only: false, cumulable: true, badge: 'verifier' },
  { id: 40, nom: 'Aide départementale', type_aide: 'subvention', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 10000, url_officielle: 'https://www.associations.gouv.fr', description: 'Subvention du conseil départemental pour les associations.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 41, nom: 'Aide Région BFC Associations', type_aide: 'subvention', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 15000, url_officielle: 'https://www.bourgognefranchecomte.fr', description: 'Subvention régionale pour les associations.', region: 'Bourgogne-Franche-Comté', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 42, nom: 'Fondation de France', type_aide: 'subvention', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 15000, url_officielle: 'https://www.fondationdefrance.org', description: 'Appels à projets thématiques de la Fondation de France.', handicap_only: false, cumulable: true, badge: 'possible' },
  { id: 43, nom: 'Mécénat d\'entreprise 60%', type_aide: 'fiscal', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 50000, taux_remboursement: 60, url_officielle: 'https://www.associations.gouv.fr', description: 'Réduction fiscale de 60% pour les entreprises mécènes.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 44, nom: 'Google Ad Grants', type_aide: 'numerique', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 10000, url_officielle: 'https://www.google.com/grants/', description: '10 000$/mois de publicité Google gratuite pour les associations.', handicap_only: false, cumulable: true, badge: 'probable' },
  { id: 45, nom: 'France Active — Garantie associative', type_aide: 'pret', profil_eligible: ['association'], situation_eligible: ['salarie', 'independant', 'demandeur_emploi'], montant_max: 30000, url_officielle: 'https://www.france-active.org', description: 'Garantie bancaire et prêt solidaire pour les associations.', handicap_only: false, cumulable: true, badge: 'possible' },
]

export function matchAides(profil: ProfilType, situation: SituationType, handicap: boolean): Aide[] {
  return AIDES_DATA
    .filter((a) => {
      if (!a.profil_eligible.includes(profil)) return false
      if (a.handicap_only && !handicap) return false
      // Associations et étudiants: pas de filtre situation strict
      if (profil === 'association' || profil === 'etudiant') return true
      return a.situation_eligible.includes(situation)
    })
    .sort((a, b) => b.montant_max - a.montant_max)
}

export function computeCumul(aides: Aide[]): number {
  return aides.reduce((sum, a) => sum + a.montant_max, 0)
}
